In [1]:
#In this notebook, we explore the various ways to add/remove columns and rows from a dataframe.
#First, we explore how to add/remove columns followed by rows.

In [23]:
import pandas as pd

In [24]:
pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',200)

In [25]:
people = {"first":["Sravan","Cruel","Suspect"],"last":["Rokkam","Goat","Glint"],"email":["sravanreddy.rokkam@gmail.com","cruelgoat@gmail.com","suspectglint@gmail.com"]}

In [26]:
df=pd.DataFrame(people)

In [27]:
df

     first    last                         email
0   Sravan  Rokkam  sravanreddy.rokkam@gmail.com
1    Cruel    Goat           cruelgoat@gmail.com
2  Suspect   Glint        suspectglint@gmail.com

In [28]:
print(df['first']+' '+df['last'])
type(df['first']+' '+df['last'])

0    Sravan Rokkam
1       Cruel Goat
2    Suspect Glint
dtype: object

pandas.core.series.Series

In [29]:
#Here we are adding a new column by assigning new series to a new column mentioned in square bracket notation.
df['full_name']=df['first']+' '+df['last']

In [30]:
df

     first    last                         email      full_name
0   Sravan  Rokkam  sravanreddy.rokkam@gmail.com  Sravan Rokkam
1    Cruel    Goat           cruelgoat@gmail.com     Cruel Goat
2  Suspect   Glint        suspectglint@gmail.com  Suspect Glint

In [31]:
#Now if we want to drop columns from a given dataframe, we can do it using .drop() method and mention the list of 
#columns to be deleted from the dataframe.
df.drop(columns=['first','last'],inplace=True)

In [32]:
df

                          email      full_name
0  sravanreddy.rokkam@gmail.com  Sravan Rokkam
1           cruelgoat@gmail.com     Cruel Goat
2        suspectglint@gmail.com  Suspect Glint

In [34]:
#Here we are splitting the full_name column into first and last using str.split() method.
#And we are also passing extra attribute expand=True to make sure the values are split into separate columns. If we donot mention
#expand, it will be a single series with list of values being split.
df['full_name'].str.split(' ',expand=True)

         0       1
0   Sravan  Rokkam
1    Cruel    Goat
2  Suspect   Glint

In [37]:
#Here we are assigning the split columns into two new columns
df[['first','last']]=df['full_name'].str.split(' ',expand=True)

In [38]:
df

                          email      full_name    first    last
0  sravanreddy.rokkam@gmail.com  Sravan Rokkam   Sravan  Rokkam
1           cruelgoat@gmail.com     Cruel Goat    Cruel    Goat
2        suspectglint@gmail.com  Suspect Glint  Suspect   Glint

In [39]:
########End of column addition and removal.##############

In [40]:
########Row addition and removal.########################

In [42]:
df

                          email      full_name    first    last
0  sravanreddy.rokkam@gmail.com  Sravan Rokkam   Sravan  Rokkam
1           cruelgoat@gmail.com     Cruel Goat    Cruel    Goat
2        suspectglint@gmail.com  Suspect Glint  Suspect   Glint

In [54]:
#df.append() method is removed in version 2.0 and is no longer used for addition of rows. Instead we use 
#df.concat() method for adding rows to a given dataframe.
df2 = pd.DataFrame({"first":["Omar","Bunk"],
       "last":["Little","Moreland"],
       "email":["omarlittle@wire.com","bunkmoreland@@wire.com"]})
df=pd.concat([df,df2],ignore_index=True)

In [55]:
df

                          email      full_name    first      last
0  sravanreddy.rokkam@gmail.com  Sravan Rokkam   Sravan    Rokkam
1           cruelgoat@gmail.com     Cruel Goat    Cruel      Goat
2        suspectglint@gmail.com  Suspect Glint  Suspect     Glint
3           omarlittle@wire.com            NaN     Omar    Little
4        bunkmoreland@@wire.com            NaN     Bunk  Moreland

In [58]:
filter=df['last']!='Moreland'
filter

0     True
1     True
2     True
3     True
4    False
Name: last, dtype: bool

In [60]:
df=df.loc[filter]

In [61]:
df

                          email      full_name    first    last
0  sravanreddy.rokkam@gmail.com  Sravan Rokkam   Sravan  Rokkam
1           cruelgoat@gmail.com     Cruel Goat    Cruel    Goat
2        suspectglint@gmail.com  Suspect Glint  Suspect   Glint
3           omarlittle@wire.com            NaN     Omar  Little