In [40]:
import pandas as pd

In [41]:
pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',200)

In [9]:
people = {"first":["Sravan Reddy","Cruel","Suspect"],"last":["Rokkam","Goat","Glint"],"email":["sravanreddy.rokkam@gmail.com","cruelgoat@gmail.com","suspectglint@gmail.com"]}

In [10]:
people

{'first': ['Sravan Reddy', 'Cruel', 'Suspect'],
 'last': ['Rokkam', 'Goat', 'Glint'],
 'email': ['sravanreddy.rokkam@gmail.com',
  'cruelgoat@gmail.com',
  'suspectglint@gmail.com']}

In [11]:
df=pd.DataFrame(people)

In [12]:
df

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [37]:
#When we compare a column of a dataframe with a static value, it returns a series of boolean values.
#This series when passed to a dataframe will return the rows satisfying the condition.
type(df['first']=='Cruel')

pandas.core.series.Series

In [38]:
#We use '|' for OR condition and '&' for AND condition when comparing between two conditions
a=(df['first']=='Cruel') | (df['last']=='Glint')

In [39]:
a,type(a)

(0    False
 1     True
 2     True
 dtype: bool,
 pandas.core.series.Series)

In [56]:
#We can also use .loc() method and pass the filter as an argument to get the filtered rows.
#And we also have the option to fetch specific columns using .loc() method"
df.loc[a]
df.loc[~a,'email']

0    sravanreddy.rokkam@gmail.com
Name: email, dtype: object

In [24]:
df[a],type(df[a])

(     first   last                   email
 1    Cruel   Goat     cruelgoat@gmail.com
 2  Suspect  Glint  suspectglint@gmail.com,
 pandas.core.frame.DataFrame)

In [47]:
b = (df['first']=='Sravan Reddy') & (df['last']=='Rokkam')

In [48]:
b,type(b)

(0     True
 1    False
 2    False
 dtype: bool,
 pandas.core.series.Series)

In [49]:
type(df.first)

method

In [50]:
type(df['first'])

pandas.core.series.Series

In [57]:
#The ~ is used to negate the filter and this will retrieve the exact opposite result set.
df[~b]

     first   last                   email
1    Cruel   Goat     cruelgoat@gmail.com
2  Suspect  Glint  suspectglint@gmail.com

In [58]:
b,~b

(0     True
 1    False
 2    False
 dtype: bool,
 0    False
 1     True
 2     True
 dtype: bool)

In [59]:
lastnames = ['Goat','Glint']

In [60]:
filter =  df['last'].isin(lastnames)

In [61]:
filter

0    False
1     True
2     True
Name: last, dtype: bool