In [1]:
#Indexes - set, reset, persist the index changes, sorting are covered in this notebook for a smaller dataframe.

In [2]:
import pandas as pd

In [3]:
people = {"first":["Sravan Reddy","Cruel","Suspect"],"last":["Rokkam","Goat","Glint"],"email":["sravanreddy.rokkam@gmail.com","cruelgoat@gmail.com","suspectglint@gmail.com"]}

In [4]:
people

{'first': ['Sravan Reddy', 'Cruel', 'Suspect'],
 'last': ['Rokkam', 'Goat', 'Glint'],
 'email': ['sravanreddy.rokkam@gmail.com',
  'cruelgoat@gmail.com',
  'suspectglint@gmail.com']}

In [6]:
df=pd.DataFrame(people)

In [7]:
df

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [8]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   3 non-null      object
 1   last    3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [31]:
#When we set an index using set_index() method, it is automatically dropped from the column list.
#And also, the changes are not persisted by default. So to make it permanent, we need to enter inplace=True.
df.set_index('email',inplace=True)

In [16]:
df

                                     first    last
email
sravanreddy.rokkam@gmail.com  Sravan Reddy  Rokkam
cruelgoat@gmail.com                  Cruel    Goat
suspectglint@gmail.com             Suspect   Glint

In [23]:
df.loc['cruelgoat@gmail.com']

first    Cruel
last      Goat
Name: cruelgoat@gmail.com, dtype: object

In [24]:
df.iloc[0]

first    Sravan Reddy
last           Rokkam
Name: sravanreddy.rokkam@gmail.com, dtype: object

In [33]:
df.reset_index(inplace=True)

In [34]:
df

                          email         first    last
0  sravanreddy.rokkam@gmail.com  Sravan Reddy  Rokkam
1           cruelgoat@gmail.com         Cruel    Goat
2        suspectglint@gmail.com       Suspect   Glint

In [37]:
#And also, if we donot want the column to be dropped while we are setting it as an index, we mention drop=False.
df.set_index('email',inplace=True,drop=False)

In [39]:
df

,email,first,last
email,,,
sravanreddy.rokkam@gmail.com,sravanreddy.rokkam@gmail.com,Sravan Reddy,Rokkam
cruelgoat@gmail.com,cruelgoat@gmail.com,Cruel,Goat
suspectglint@gmail.com,suspectglint@gmail.com,Suspect,Glint